export default [
    {code: "ar-SA", title: "Arabic - Saudi Arabia"},
    {code: "bn-BD", title: "Bangla - Bangladesh"},
    {code: "bn-IN", title: "Bangla - India"},
    {code: "cs-CZ", title: "Czech - Czech Republic"},
    {code: "da-DK", title: "Danish - Denmark"},
    {code: "de-AT", title: "German - Austria"},
    {code: "de-CH", title: "German - Switzerland"},
    {code: "de-DE", title: "German - Germany"},
    {code: "el-GR", title: "Greek - Greece"},
    {code: "en-AU", title: "English - Australia"},
    {code: "en-CA", title: "English - Canada"},
    {code: "en-GB", title: "English - United Kingdom"},
    {code: "en-IE", title: "English - Ireland"},
    {code: "en-IN", title: "English - India"},
    {code: "en-NZ", title: "English - New Zealand"},
    {code: "en-US", title: "English - United States"},
    {code: "en-ZA", title: "English - South Africa"},
    {code: "es-AR", title: "Spanish - Argentina"},
    {code: "es-CL", title: "Spanish - Chile"},
    {code: "es-CO", title: "Spanish - Columbia"},
    {code: "es-ES", title: "Spanish - Spain"},
    {code: "es-MX", title: "Spanish - Mexico"},
    {code: "es-US", title: "Spanish - United States"},
    {code: "fi-FI", title: "Finnish - Finland"},
    {code: "fr-BE", title: "French - Belgium"},
    {code: "fr-CA", title: "French - Canada"},
    {code: "fr-CH", title: "French - Switzerland"},
    {code: "fr-FR", title: "French - France"},
    {code: "he-IL", title: "Hebrew - Israel"},
    {code: "hi-IN", title: "Hindi - India"},
    {code: "hu-HU", title: "Hungarian - Hungary"},
    {code: "id-ID", title: "Indonesian - Indonesia"},
    {code: "it-CH", title: "Italian - Switzerland"},
    {code: "it-IT", title: "Italian - Italy"},
    {code: "ja-JP", title: "Japanese - Japan"},
    {code: "ko-KR", title: "Korean - Republic of Korea"},
    {code: "nl-BE", title: "Dutch - Belgium"},
    {code: "nl-NL", title: "Dutch - The Netherlands"},
    {code: "no-NO", title: "Norwegian - Norway"},
    {code: "pl-PL", title: "Polish - Poland"},
    {code: "pt-BR", title: "Portugese - Brazil"},
    {code: "pt-PT", title: "Portugese - Portugal"},
    {code: "ro-RO", title: "Romanian - Romania"},
    {code: "ru-RU", title: "Russian - Russian Federation"},
    {code: "sk-SK", title: "Slovak - Slovakia"},
    {code: "sv-SE", title: "Swedish - Sweden"},
    {code: "ta-IN", title: "Tamil - India"},
    {code: "ta-LK", title: "Tamil - Sri Lanka"},
    {code: "th-TH", title: "Thai - Thailand"},
    {code: "tr-TR", title: "Turkish - Turkey"},
    {code: "zh-CN", title: "Chinese - China"},
    {code: "zh-HK", title: "Chinese - Hond Kong"},
    {code: "zh-TW", title: "Chinese - Taiwan"}
];
